spring:
  application:
    name: EUREKA-HA
  profiles:
    active: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://user:812912@peer2:8762/eureka/,http://user:812912@peer1:8761/eureka/

security:
  basic:
    enabled: true  #开启安全配置，  也就是需要密码， 注意这个参数必须放在application.yml中
  user:
    name: user
    password: 812912  #  配置了用户名和密码后可以修改密码的访问风格为curl风格