server:
  port: 8300
spring:
  application:
    name: consumerorder-hystrix-turbine2
user:
  url: http://localhost:7900/user/
eureka:
  client:
    service-url:
      defaultZone: http://user:812912@localhost:10000/eureka
turbine:
  aggregator:
    clusterConfig: default
  appConfig: consumerorder-hystrix,consumerorder-feign-hystrix
  cluster-name-expression: "'default'"